### ISSUE TITLE
No inverse trigonometric functions, inconsistent with English naming `tg` operation

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#104]
There are no inverse trigonometric functions in `ExtendedField` and related algebras. I'm sure they have some usecases.

`tg` abbreviation for tangent is inconsistent with modern English notation. 

This issue is filed in the main for discussing PR #99.

**Comment by altavir** [comment]
The vote in kotlin slack is in favor of tan, so this one is agreed, the rest waits for intermediate PRs to be merged.

**Comment by altavir** [comment]
fixed via #114
