### ISSUE TITLE
List ojAlgo features to port to KMath

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#132]
#66 can't be implemented without set of features that needed in KMath.

**Comment by altavir** [comment]
Could you be more specific? Ojalgo is huge. I suggest to start with linear algebra and then proceed when there are future requests. The same way we are doing to for commons-math.

**Comment by CommanderTvis** [comment]
> Could you be more specific? Ojalgo is huge. I suggest to start with linear algebra and then proceed when there are future requests. The same way we are doing to for commons-math.

OK
