### ISSUE TITLE
kmath with maven - POM for scientifik:kmath-core-jvm:jar:0.13 is missing

### ISSUE THREAD

**Issue by sorokod** [mipt-npm/kmath#133]
I'd like to include kmath as dependency in a maven project. In pom.xml I have

    <repositories>
        <repository>
            <id>bintray</id>
            <url>https://dl.bintray.com/mipt-npm/scientifik</url>
        </repository>
    </repositories>
  
and

            <dependency>
                <groupId>scientifik</groupId>
                <artifactId>kmath-core-jvm</artifactId>
                <version>0.13</version>
            </dependency>

but when trying to build the project with maven I get:

```
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://jcenter.bintray.com/scientifik/kmath-core-jvm/0.13/kmath-core-jvm-0.13.pom
Downloading from bintray: https://dl.bintray.com/mipt-npm/scientifik/scientifik/kmath-core-jvm/0.13/kmath-core-jvm-0.13.pom
[WARNING] The POM for scientifik:kmath-core-jvm:jar:0.13 is missing, no dependency information available
Downloading from central: https://jcenter.bintray.com/scientifik/kmath-core-jvm/0.13/kmath-core-jvm-0.13.jar
Downloading from bintray: https://dl.bintray.com/mipt-npm/scientifik/scientifik/kmath-core-jvm/0.13/kmath-core-jvm-0.13.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.930 s
[INFO] Finished at: 2020-09-06T13:29:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project consoleApp: Could not resolve dependencies for project me.xor:consoleApp:jar:1.0-SNAPSHOT: Could not find artifact scientifik:kmath-core-jvm:jar:0.13 in central (https://jcenter.bintray.com) -> [Help 1]
[ERROR] 
```

**Comment by altavir** [comment]
It seems like You wrote the wrong version, it should be `0.1.3`, not `0.13`. It should be accessible through maven (https://bintray.com/mipt-npm/scientifik/kmath-core/0.1.3).

We plan to add jcenter publication alongside with new package naming and rebranding (`scientifik` -> `kscience.kmath`) in the next major release.

**Comment by sorokod** [comment]
Thanks - that was indeed the issue.
