### ISSUE TITLE
LazyMatrix class in the core module?

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#147]
That's weird that there is VirtualMatrix class with each time calculated values, but there are no lazy matrices having supplier function and underlying matrix to store calculated values.

**Comment by altavir** [comment]
Lazy matrices are here: https://github.com/mipt-npm/kmath/blob/master/kmath-coroutines/src/jvmMain/kotlin/scientifik/kmath/structures/LazyNDStructure.kt. I do not remember why, probably because it requires both coroutines and runblocking.
