### ISSUE TITLE
GroupId in ReadMe for 0.1.4 is wrong

### ISSUE THREAD

**Issue by breucode** [mipt-npm/kmath#152]
When adding KMath to my application, I get an error with version 0.1.4, because gradle can't find the artifact.

From 0.1.4 onwards `kscience.kmath` must be used as a groupId instead of `scientifik`

**Comment by altavir** [comment]
Thank you. It is fixed in dev branch. There is confusion with 0.1.4. I will hot-patch readme now, but it will all be fixed with 0.2.0 release (we will have new readme generator.
