### ISSUE TITLE
Jetbrains research badge in ReadMe.md

### ISSUE THREAD

**Issue by breucode** [mipt-npm/kmath#153]
According to https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub (which the ReadMe links to from the JetBrains Research Badge), the corresponding badges must only be used by Repositories under the Kotlin and JetBrains organizations.

However, this repository also has the JetBrains research projects badge. I suppose this should be removed to avoid confusion.

Can someone elaborate on this?

**Comment by CommanderTvis** [comment]
This project belongs to MIPT-NPM laboratory which has joined JetBrains Research in 2019. 
![image](https://user-images.githubusercontent.com/38042667/96292088-3e440400-1013-11eb-804b-cc1ecdc52b79.png)

**Comment by CommanderTvis** [comment]
https://research.jetbrains.org/groups/npm

**Comment by altavir** [comment]
@breucode Jetbrains indeed takes responsibility only for official projects. Still, JetBrains research is an international scientific organization that includes laboratories outside JetBrains. Our laboratory is indeed an official part of it and so we are marking repositories directly connected to our work in JBR. JB is not responsible for the code though.

**Comment by altavir** [comment]
Here is the project page on JBR: https://research.jetbrains.org/groups/npm/projects?project_id=39

**Comment by breucode** [comment]
Thanks for the clarification, that helped me a lot.
