### ISSUE TITLE
A general decision on treatments of NaNs

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#157]
Should complex number and quaternion structures be NaN-hostile?

**Comment by altavir** [comment]
I think that NaNs should be completely forbidden in all sensitive places. In my experience, it causes a lot of undebuggable problems. Missing values could be treated as nullable. Therefore encountering a NaN in place, which is sensitive to it should lead to an error.

**Comment by altavir** [comment]
cc @pklimai @breandan @Shimuuar

**Comment by Zelenyy** [comment]
If complex type depend on Double, you can't avoid NaN value

**Comment by altavir** [comment]
We can avoid treating them and fail-fast if we encounter them.

**Comment by CommanderTvis** [comment]
#156 depends on it, since I can't decide if quaternion should handle NaN components in all the operations or simple be NaN-hostile.

**Comment by altavir** [comment]
I think that we can safely assume zero NaN tolerance strategy for now. We can add them later if we want.

**Comment by CommanderTvis** [comment]
By the way. Why can't we make RealField and FloatField hostile to NaN. It can add some performance loses, but it will be consistent with making Complex (and Quaternion in future) NaN-hostile.

**Comment by altavir** [comment]
Performance losses should be avoided in performance-optimized algebras at all costs.
