### ISSUE TITLE
Inconsistent endianness on different KMath platforms

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#161]
In `kmath-memory` module, different platform implementations provide different endianness, so they can't be used for persistent serialization.

1. JS - Big Endian.
2. JVM - platform byte order.
3. Native - Littel Endian.

The solution is to make all the memory implementations use Little Endian byte order, since Kotlin/Native can only use it.

**Comment by altavir** [comment]
It is a good question.

On JVM it always uses Big Endian, see [allocate documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html#allocate(int)). Why do you think that native uses Lttle Endian?

**Comment by altavir** [comment]
The `Memory` interface does not specify the layout of the memory, so the byte order could be different on different platforms. Actually, I was thinking about using [Apache Arrow](https://arrow.apache.org/) as an alternative memory representation for communication between platforms.

**Comment by CommanderTvis** [comment]
> It is a good question.
> 
> On JVM it always uses Big Endian, see [allocate documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html#allocate(int)). Why do you think that native uses Little Endian?

Since it is documented
![image](https://user-images.githubusercontent.com/38042667/101318439-ed25f300-3892-11eb-9f2c-7b75d0918203.png)

**Comment by altavir** [comment]
Indeed. This is from ByteArray native extensions. Still, I do not think that we need to change that. We can provide alternative platform-consistent memory.

**Comment by CommanderTvis** [comment]
Should be covered within #98

**Comment by CommanderTvis** [comment]
Should be covered within #432
