### ISSUE TITLE
Impossible to define exponential function in kmath-ast

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#166]
It is really impossible to define an exponential function node in `kmath-ast` like `x^y`. 

The problem is that actual RealField does not provide an operation for exponentiating an element, and it makes expressions API quite limited.

Expected syntax:

```kotlin
MstExtendedField { x pow y }.toExpression(DoubleField)(x to 2.0, y to 1024.0)
```

**Comment by altavir** [comment]
I do not really like the design of `mstInAlgebra` operations. I expect it to be completely deprecated with the arrival of multiple receivers. There will be a separate MST builder class that will have a generic marker parameter designating, which operations are allowed inside it. Actual operations will be moved to extensions and dispatched based on this generic parameter. In this case, the builder will inherit the parameter from the algebra it is called upon.

**Comment by CommanderTvis** [comment]
Sounds nice, but multirecevier is 1.5 or 1.6+ feature
