### ISSUE TITLE
Artifacts not available

### ISSUE THREAD

**Issue by bjonnh** [mipt-npm/kmath#243]
Trying what is given in the README:

````
repositories {
    maven("https://repo.kotlin.link")
}

dependencies {
    api("kscience.kmath:kmath-core:0.2.0")
    // api("kscience.kmath:kmath-core-jvm:0.2.0") for jvm-specific version
}
````

This doesn't find the packages I had to add -dev-7 to the version.

**Comment by CommanderTvis** [comment]
Use the `space.kscience:kmath-core:0.2.0` artifact. We'll update the README as soon as possible.

**Comment by altavir** [comment]
Here is the link to the maven-central page: https://search.maven.org/artifact/space.kscience/kmath-core/0.2.1/jar We had to change the package to publish to central. And 0.2.0 published with errors.

**Comment by altavir** [comment]
I've fixed the landing by merging the dev branch. As @CommanderTvis said, we will work on the documentation and make it better in 0.3. The Jupyter integration module will be added soon as well (#246).

**Comment by bjonnh** [comment]
Thanks! I appreciate the efforts.
