### ISSUE TITLE
MST: Add `symbol` delegate provider for tuples

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#282]
Use case:
```
val (x, y) by symbol // symbol: ReadOnlyProperty<Any?, Pair<Symbol, Symbol>>
```

**Comment by CommanderTvis** [comment]
Not sure if it is possible

**Comment by altavir** [comment]
I think it is possible, but it does not make any sense. Saving lines on symbols seems useless.

**Comment by CommanderTvis** [comment]
It's beautiful

**Comment by altavir** [comment]
I see no valid use-case for it. So `won't fix` unless you  give some reasoning beyond one line in the  whole project economy.

**Comment by CommanderTvis** [comment]
It isn't possible
![image](https://user-images.githubusercontent.com/38042667/119667864-dc793180-be60-11eb-8157-ec164b6fdfdc.png)
