### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by breandan** [mipt-npm/kmath#32]
It looks like the [build artifacts](http://npm.mipt.ru:8081/artifactory/gradle-dev/scientifik/kmath-core/) are outdated. [TeamCity](https://teamcity.jetbrains.com/project.html?projectId=OpenSourceProjects) offers free builds for OSS, as well as [Travis CI](https://travis-ci.com/) or [CircleCI](https://circleci.com/). It is possible to autobuild on a per-commit basis, and [publish releases](https://docs.gradle.org/current/userguide/publishing_overview.html#sec:basic_publishing) to a custom Maven repository. Please let me know if you need any help setting this up.

**Comment by Shimuuar** [comment]
I used travis CI for haskell projects and it works reasonably nice. Generally CI is most useful to ensure that commits/PR do not break anything or that library could at least be built. It's surprisingly easy to submit PR that is not even buildable

**Comment by altavir** [comment]
Not that I have a lot of PR so far. I will finish basic functionality soon, then CI integration PR would be welcome. Also we need to decide on repository. Self-hosted artifactory is OK for internal use, but is not very stable. I can try to configure JCenter bucket.

**Comment by altavir** [comment]
Postponed. No need right now.

**Comment by altavir** [comment]
We have github actions now. I do not think, that we need anything else for now.

**Comment by altavir** [comment]
TeamCity would be nice though...

**Comment by altavir** [comment]
I think I will close that. GH-actions suits our needs. Also, Space CI is out, so it will cover more sophisticated cases.
