### ISSUE TITLE
Consider redesign of `MemoryReader.release` and `MemoryWriter.release`

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#378]

**Comment by altavir** [comment]
I agree, but I do not have any clear ideas about what to do with them. I think it will be more clear when we have some kind of prototype of working with native or memory-mapped blocks.

**Comment by CommanderTvis** [comment]
Well, current usages of `Memory` inside the library rely on that off-heap memory is managed by GC.

**Comment by CommanderTvis** [comment]
So, either we have either to carefully use such objects like `MemoryBuffer` inside certain scopes or not to use really native memory without any hacks like `Cleaner`.

**Comment by CommanderTvis** [comment]
> I agree, but I do not have any clear ideas about what to do with them. I think it will be more clear when we have some kind of prototype of working with native or memory-mapped blocks.

An obvious prototype of usage managed native objects is [kmath-gsl](https://github.com/mipt-npm/kmath-gsl).

**Comment by altavir** [comment]
We need this interface to be usable both for managed and for non-managed memory. So there should be some kind of either release method or strict scoping policy. It does not make a lot of sense for only managed memory. I am not quite sure right now, but I think that there should be a release method like it is now, and the scoping rules should be built on top of it.

**Comment by CommanderTvis** [comment]
Maybe we should separate managed memory for things like `MemoryBuffer` from manual one?

**Comment by CommanderTvis** [comment]
Closing because of #432
