### ISSUE TITLE
Univariate and multivariate functions

### ISSUE THREAD

**Issue by altavir** [mipt-npm/kmath#39]
Similar to http://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/index.html, but in more kotlinish way. Add commons-math back-end implementation for jvm.

Special class for polynomials, maybe also for specific functions like normal, Cauchy, etc.

**Comment by Mizgala** [comment]
I've been working on this feature but I've run into a bit of a snag. One of the classes needed for the `PolynomialFunction ` class in the Apache commons implements the `FieldElement` and `RealFieldElement` interfaces. However the `FieldElement` interface in KMath takes a type and a context while the one in Apache only takes a type. Is this just the way this interface is implemented in KMath or do these interfaces serve different functions?

**Comment by altavir** [comment]
The behavior of field elements in kmath and commons-math is very similar. In fact, I took inspiration from them. The difference is that in commons-math, fields are not contexts (Java does not have them). So, `FieldElement` stores all of the operations and `Field` contains only `one`s and `zero`s. All operations are performed on elements and algebras are secondary. The drawback of this approach is that you can't perform operations on arbitrary types, only on ones inherited from `FieldElement`. 

In kmath, kotlin lexical contexts allow to take operations directly from the algebra class. So in our case, the primary work horse is the context (`Algebra`), which declares operations on any type it wants. Usual types do not have operations, because it is possible to define different operations on the same type. An `Element` is just a typed object coupled to one single fixed `Algebra`. I think that in general, they are second class citizens. So we should focus on algebras themselves thirst. By the way, there should be a `Space` or even a `Ring` for polynomials, it makes sense and easy to implement.

I think, that in next release, I will split operations in `Algebra` from neutral elements, thus making it closer to commons-math. It won't affect external API. I need it because in many cases we do not need neutral elements and operations without them could be defined as singletons.

**Comment by altavir** [comment]
The documentation for all that is [here](https://github.com/altavir/kmath/blob/dev/doc/algebra.md). Please open an issue or contribute changes to it if you feel like it.

**Comment by altavir** [comment]
Sticking to kotlin functions for now: https://github.com/mipt-npm/kmath/blob/dev/kmath-functions/src/commonMain/kotlin/space/kscience/kmath/functions/functionTypes.kt

Argument naming done with https://github.com/mipt-npm/kmath/blob/8974164ec05dcfa5feab830cfa8223291e1dbb79/kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/SymbolIndexer.kt scope
