### ISSUE TITLE
`PiecewisePolynomial<T>.integrate` isn't annotated with `PerformancePitfall`

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#393]

**Comment by altavir** [comment]
Why should it? It should be pretty fast since it is analytical.

**Comment by CommanderTvis** [comment]
```
@PerformancePitfall("findPiece method of resulting piecewise is slow")
public fun <T : Comparable<T>> PiecewisePolynomial(
```

**Comment by altavir** [comment]
If I remember correctly, it does not search pieces, but maps them, which is a linear operation. Also performance is relative, it is much faster than regular integration.
