### ISSUE TITLE
Avoid using `kapt` in `kmath-jupyter`

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#398]
This is necessary because there are problems with running `kapt` on JDK 16.

**Comment by altavir** [comment]
The jupyter plugin uses kapt, so this issue must be addressed [there](https://github.com/Kotlin/kotlin-jupyter)

**Comment by CommanderTvis** [comment]
> The jupyter plugin uses kapt, so this issue must be addressed [there](https://github.com/Kotlin/kotlin-jupyter)
https://github.com/Kotlin/kotlin-jupyter/blob/master/docs/libraries.md#avoiding-using-annotation-processor
