### ISSUE TITLE
Consider AsciiDoc as format of documentation in the repository

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#414]

**Comment by altavir** [comment]
Any reasons for that? Markdown is much more widely accepted and formats are more or less equivalent.

**Comment by CommanderTvis** [comment]
> Any reasons for that? Markdown is much more widely accepted and formats are more or less equivalent.

There are.
1. AsciiDoc is supported by GitHub, and this is the only place where format acceptance counts.
2. There are LOTS of features that Markdown hasn't: table of contents, convenient element anchors for navigation, delimited blocks as well as other layout elements, text replacements (rendering `->` as → and so on).

**Comment by altavir** [comment]
GitHub is not the only place that counts. Space is Markdown-oriented as well as a lot of other tools. So won't fix. If we want to us some kind of nicer format, we should finish SNARK first.

**Comment by CommanderTvis** [comment]
> GitHub is not the only place that counts. Space is Markdown-oriented as well as a lot of other tools. So won't fix. If we want to us some kind of nicer format, we should finish SNARK first.

1. GitHub only renders [these formats](https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#rendering-differences-in-prose-documents), so we'll be forced to store both SNARK sources and compiled files.
   * Markdown
   * AsciiDoc
   * Textile
   * ReStructuredText
   * Rdoc
   * Org
   * Creole
   * MediaWiki
   * Pod
2. SNARK requires tremendous efforts incomparable with just changing file extensions in `/docs` from `.md` to `.adoc` (because AsciiDoc is mostly a superset of Markdown).
3. Markdown really limits any practical use of the documentation; for me, it really was a disincentive to improve it.

**Comment by altavir** [comment]
SNARK could be compiled to Markdown or even plain HTML (and you can use HTML in markdown for layouting etc). Why not use HTML?

**Comment by CommanderTvis** [comment]
> SNARK could be compiled to Markdown or even plain HTML (and you can use HTML in markdown for layouting etc). Why not use HTML?

Pure HTML isn't displayed by GitHub.

**Comment by altavir** [comment]
Pure HTML in Markdown is displayed quite fine.

**Comment by CommanderTvis** [comment]
> Pure HTML in Markdown is displayed quite fine.

OK, that's true, but there is still point (2).
