### ISSUE TITLE
`Polynomial` is suboptimal for functions like `x^1231243+2x`

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#446]
`Polynomial` is suboptimal for functions like `x^1231243+2x` because they cause huge padding in the internal list.

The obvious solution is to extract the `get` method into interface `Polynomial` and implement it with value class over `List` as well as a new value class over `Map<Int, Int>`.

**Comment by lounres** [comment]
I guess the issue can be closed now.
