### ISSUE TITLE
MST: Constant folding pass

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kmath#454]

**Comment by altavir** [comment]
Initially there was constant folding for numbers, but there was some problems with it (I don't remember which). I think there are two ways to do that:

1. Introduce a transformation that does constant folding (we need transformation API anyway).
2. Do a special block inside mst builder that does constant folding win number algebra. Something along the lines of coroutines `withContext`, but `withAlgebra`.

Maybe both.

**Comment by CommanderTvis** [comment]
> Initially there was constant folding for numbers, but there was some problems with it (I don't remember which). I think there are two ways to do that:
> 
> 1. Introduce a transformation that does constant folding (we need transformation API anyway).
> 2. Do a special block inside mst builder that does constant folding win number algebra. Something along the lines of coroutines `withContext`, but `withAlgebra`.
> 
> Maybe both.

I think the first option is better because when one uses the `MST` builder they expect the resulting structure to correspond with the code they have written.

**Comment by CommanderTvis** [comment]
Creating a visitor for folding would allow us to fold constants under the hood.

**Comment by CommanderTvis** [comment]
Actually, we can do folding not only for `Numeric` operands but for `Symbol`s too&mdash;if they hold constants like `pi`.

**Comment by altavir** [comment]
As I said, I've done it initially. I don't remember, why we removed it. If we did..
