### ISSUE TITLE
Kmath-ast dokka build fails due to incorrect treatment of js sources

### ISSUE THREAD

**Issue by altavir** [mipt-npm/kmath#467]
` KLIB path has unexpected extension: /home/runner/work/kmath/kmath/build/js/node_modules/astring/dist/astring.js`

**Comment by CommanderTvis** [comment]
Related to https://github.com/Kotlin/dokka/issues/1479

**Comment by IgnatBeresnev** [comment]
Hi! Possible fix was released in [1.6.10](https://github.com/Kotlin/dokka/releases/tag/v1.6.10), can you give it a try?

**Comment by CommanderTvis** [comment]
@altavir Yes, everything is built correctly with Dokka 1.6.10. Please, ensure that our version catalog in the Space repo is actual.
