### ISSUE TITLE
Kotlin 1.7.10 support

### ISSUE THREAD

**Issue by NorbertSandor** [mipt-npm/kmath#496]
I've seen that Kotlin 1.7 support is already baked into the `dev` branch.
Would it be possible to release an official version with this feature?

**Comment by altavir** [comment]
You can use KMath stable with Kotlin 1.7 just fine. I do not think it relies on any features that were deprecated in 1.7. Also I will soon release another dev version with new features. But it won't be better in terms of interoperability.
