### ISSUE TITLE
ND4J

### ISSUE THREAD

**Issue by altavir** [mipt-npm/kmath#52]
Add implementation of `NDStructure` with ND4J

**Comment by CommanderTvis** [comment]
Isn't ND4J unsupported?
![image](https://user-images.githubusercontent.com/38042667/82154067-b906c880-9895-11ea-9322-01b8ae9542da.png)

**Comment by altavir** [comment]
@CommanderTvis No, it is now a part of DeepLerning4j and is integrated in its repository: https://github.com/eclipse/deeplearning4j/tree/master/nd4j

**Comment by breandan** [comment]
You might also want to check out the [SIG JVM](https://groups.google.com/a/tensorflow.org/forum/#!forum/jvm) mailing  and [ndarray](https://groups.google.com/g/java-ndarray-standardization/c/9xTDIAZGLfo) mailing lists if you haven't seen them. TensorFlow for Java has another [ND array](https://github.com/tensorflow/java/tree/master/ndarray) implementation and there appears to be a [shared interest](https://github.com/awslabs/djl/issues/1) in developing community standards here, I'm sure they could benefit from your input. cc: @mkhalusova

**Comment by altavir** [comment]
Thanks, @breandan. We can add different implementations as well since we have a highly modular environment here. The experience with Commons-Math and Koma shows that we can do under-hood matrix inner transformations and actually do operations with different inner formats simultaneously. As you can see the implementation of the connector requires only few lines of code.

**Comment by breandan** [comment]
Is KMath interested in maintaining a module/package for translating between various JVM ND array libraries? I've written [a few](https://github.com/breandan/kotlingrad/blob/40f0b7d7fbb647090f707d3809233790f41d54d0/core/src/test/kotlin/edu/umontreal/kotlingrad/perf/SparseTest.kt#L73-L86) and might be able to submit a PR for this.

**Comment by altavir** [comment]
It would be nice. But the idea we currently try to implement is to be able to make library-specific operations from inside of Kmath. It requires not only implementing converters, but also ND algebra wrappers. The idea is the format is defined by the algebra. As long as you use a nd-array implementation native to this algebra, you are getting almost zero overhead on operations, but it you try to use foreign matrix it is implicitly converted to the native format, This way, we do not get performance loss on format conversion when we do all maths in the same format. Only when we are combining different implementations.
