### ISSUE TITLE
Support for Probability Distributions

### ISSUE THREAD

**Issue by Moriand** [mipt-npm/kmath#54]
Hi, Is there any way to include these components?
[Url apache commons math](https://commons.apache.org/proper/commons-math/userguide/distribution.html)

  - distribution normal
  - distribution t-student
  - distribution chi-square
  - distribution F-fisher

for example
```
f.cumulativeProbability(x)
f.probability(x)
f.inverseCumulativeProbability(p)

//    example t-student distribution

TDistribution t = new TDistribution(29);
double lowerTail = t.cumulativeProbability(-2.656);     // P(T(29) <= -2.656)
double upperTail = 1.0 - t.cumulativeProbability(2.75); // P(T(29) >= 2.75)

```

**Comment by altavir** [comment]
It is planned (see #35). Currently you can just add a `kmath-commons` dependency and access those from any jvm project (it uses commons-math as a transitive dependency). It is planned to move a little bit further though. I plan to:

- [ ] Create a modern kotlin-friendly API.

- [ ] Add implementation of those API for commons-math.

- [ ] Create a multiplatform analog.

I have my plate full at the moment and will return to it in few weeks. For now I would be very happy if you have any suggestions for API. You can look into my [previous prototype project](https://bitbucket.org/Altavir/dataforge/src/dev/dataforge-stat/) for inspiration. I was writing it few years ago so I do not really remember what is it there.

**Comment by Moriand** [comment]
- [x] Add implementation of those API for commons-math.

that seems better to me, the more bookstores there are, the better the kotlin language

**Comment by altavir** [comment]
Basic random support for JVM added via 1b647b60142f630342fe7ea61be3231d77a07b48

**Comment by altavir** [comment]
There were problems with commons-math two-direction compatibility for random generators, so it is replaced by more modern commons-rng (does not need kmath-commons anymore). Sadly, I had to sacrifice some existing distribution sampling. We need to reimplement those using samplers, provided by commons-rng.

**Comment by breandan** [comment]
Would be nice to support for sampling from a discrete/enumerated distribution a la [commons-math](https://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math4/distribution/EnumeratedDistribution.html) / [hipparchus](https://www.hipparchus.org/apidocs/org/hipparchus/distribution/EnumeratedDistribution.html).

**Comment by altavir** [comment]
@breandan It should be possible right now with [rng discrete sampler](https://commons.apache.org/proper/commons-rng/commons-rng-sampling/apidocs/org/apache/commons/rng/sampling/DiscreteProbabilityCollectionSampler.html), but we will add a nice builder for it. @CommanderTvis is on the crusade to reimplement all those samplers in the multiplatform, but it still requires some work.

**Comment by altavir** [comment]
Mostly implemented. Should create PRs for additional distributions
