### ISSUE TITLE
Support for BigInteger

### ISSUE THREAD

**Issue by mccorby** [mipt-npm/kmath#69]
Secure multi-party computation (SMPC) and related mechanisms work with numbers that exceed the maximum values of Kotlin primitive types.

By adding support to `BigInteger`, components using KMath could be used in SMPC setups.

An interesting field where this could be applied is to training and inference of machine learning algorithms where the data is never shared.

**Comment by altavir** [comment]
It is quite easy to add support for `BigInteger` just by adding new `Space` for them. It will make them available to the most of mechanisms inside `kmath` including nd-structures. Do you have some additional requirements? And do you need a multiplatform implementation?

**Comment by mccorby** [comment]
We are targeting the JVM right now but we'll go multiplatform in the future.

**Comment by altavir** [comment]
I've added a basic support for BigInteger in the dev branch (see 651f832). Now you can create buffers and nd-structures with BigInteger and operate with them inside appropriate contexts. But I still do not have a clear understanding about what algorithms do you need so, I don't now where to move next. 

A little warning: BigInteger operations will be rather expensive. The binary representation has a variable length so it is not possible to achieve even the level of performance of `Complex`. If you have some performance critical part, we'd better think about a special internal representation like 12-bit integers (short-int pairs).

**Comment by mccorby** [comment]
I will play with the PR. It looks good. I had started myself but... you're faster and know where to add the code!

We are still in an early state of the project but having support for BigInteger is essential. Basic operations (add, mul) on matrices will be ones to start with so I guess this PR already covers it.

Thanks

**Comment by altavir** [comment]
Addition and multiplication are provided by Kotlin stdlib out of box, so you do not need Kmath for that. I've added ND-structures but not matrix operations (like matrix product and inversion). You need to remember that ND-operations are element by element not linear algebra. As far as I remember, I need only two additional lines to add them, but I will wait for your input here or in slack.

**Comment by altavir** [comment]
Mutliplatform BigInt implemented by #81
