### ISSUE TITLE
Improper square for complex numbers

### ISSUE THREAD

**Issue by gt22** [mipt-npm/kmath#74]
Currently, complex number square is defined as follows:
https://github.com/mipt-npm/kmath/blob/f931004b5c3564c66c483909825d98cb2c7f74c2/common/src/main/kotlin/scientifik/kmath/operations/Fields.kt#L69-L70

But that is not square of complex number (z^2), it's square of it's norm (|z|^2).

It should be defiend as:
```kotlin
val square: Complex
        get() = Complex(re * re - im * im, 2 * re * im)
```

**Comment by altavir** [comment]
You are correct, thank you. I am not sure what I was thinking about, when I wrote that. Probably about vectors.
